FROM pppepito86/judgebox

RUN apt-get update
RUN apt-get install python -y
RUN apt-get install -y nodejs
RUN apt-get install ghc -y
RUN apt-get install -y curl
RUN apt-get install gcc -y
RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh
